// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBevibh-YdJuP9-DLpbb93n5atmUQ3pwhs',
    appId: '1:799045719295:web:1c27841e84f0dd9f0de8ca',
    messagingSenderId: '799045719295',
    projectId: 'salv-4c518',
    authDomain: 'salv-4c518.firebaseapp.com',
    databaseURL: 'https://salv-4c518-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'salv-4c518.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqaIy7aqAhyEWSjlO3PiKaOMwZUiMv8Ds',
    appId: '1:799045719295:android:fb575d38c9d19d020de8ca',
    messagingSenderId: '799045719295',
    projectId: 'salv-4c518',
    databaseURL: 'https://salv-4c518-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'salv-4c518.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk3-vj3GOYp377eStnxk_5zJEZwHMY2No',
    appId: '1:799045719295:ios:4ceb8e1f7857f0d70de8ca',
    messagingSenderId: '799045719295',
    projectId: 'salv-4c518',
    databaseURL: 'https://salv-4c518-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'salv-4c518.appspot.com',
    iosClientId: '799045719295-d2laqcjvjhl13hu9kbf6pjtendh6dgfk.apps.googleusercontent.com',
    iosBundleId: 'com.example.salv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk3-vj3GOYp377eStnxk_5zJEZwHMY2No',
    appId: '1:799045719295:ios:4ceb8e1f7857f0d70de8ca',
    messagingSenderId: '799045719295',
    projectId: 'salv-4c518',
    databaseURL: 'https://salv-4c518-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'salv-4c518.appspot.com',
    iosClientId: '799045719295-d2laqcjvjhl13hu9kbf6pjtendh6dgfk.apps.googleusercontent.com',
    iosBundleId: 'com.example.salv',
  );
}
